export enum ApiErrorCodes {
  EMAIL_ALREADY_IN_USE = "EMAIL_ALREADY_IN_USE",
  ENTITY_NOT_FOUND = "ENTITY_NOT_FOUND",
  INVALID_CREDENTIALS = "INVALID_CREDENTIALS",
  MAX_IMAGES_REACHED = "MAX_IMAGES_REACHED",
  NON_ADMIN_PRIVILEGES = "NON_ADMIN_PRIVILEGES",
  TOKEN_NOT_VALID = "TOKEN_NOT_VALID",
  USERNAME_ALREADY_IN_USE = "USERNAME_ALREADY_IN_USE",
}
